import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

function Home({ categories }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <Link href="/" passHref>
            Home
          </Link>
          <Link href="/events" passHref>
            Events
          </Link>
          <Link href="/about" passHref>
            About
          </Link>
        </nav>
      </header>

      <main>
        <div>
          {categories.map((category) => (
            <Link key={category.id} href={`/events/${category.id}`} passHref>
              <Image
                src={category.image}
                alt={category.title}
                width={300}
                height={300}
              />
              <h2>{category.title}</h2>
              <p>{category.description}</p>
            </Link>
          ))}
        </div>
      </main>

      <footer>Footer</footer>
    </>
  );
}

export async function getServerSideProps(context) {
  const { categories } = await import("/data/db.json");
  return {
    props: {
      categories,
    },
  };
}

export default Home;
