import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          {/* <Image src="" alt="" /> */}
          <Link href="/">Home</Link>
          <Link href="/events">Events</Link>
          <Link href="/about">About</Link>
        </nav>
      </header>
      <main className={styles.main}>
        <div>
          <Link href="">
            {/* <Image src="" alt="" /> */}
            <h2>Events in London</h2>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid
              impedit nam reprehenderit itaque laborum in, odio beatae et soluta
              quo magnam a eaque veritatis obcaecati ex nulla totam architecto
              aspernatur?
            </p>
          </Link>
          <Link href="">
            {/* <Image src="" alt="" /> */}
            <h2>Events in San Francisco</h2>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid
              impedit nam reprehenderit itaque laborum in, odio beatae et soluta
              quo magnam a eaque veritatis obcaecati ex nulla totam architecto
              aspernatur?
            </p>
          </Link>
          <Link href="">
            {/* <Image src="" alt="" /> */}
            <h2>Events in Barcelona</h2>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid
              impedit nam reprehenderit itaque laborum in, odio beatae et soluta
              quo magnam a eaque veritatis obcaecati ex nulla totam architecto
              aspernatur?
            </p>
          </Link>
        </div>
      </main>

      <footer>Footer</footer>
    </>
  );
}
